GDSC-MITS/Contribute-To-HacktoberFest

Hello World Programs/hello_world.c

A hello world program written in C.

Hello World!

---

Sorting/bubble_sort.cpp
Sorting/insertion_sort.cpp
Sorting/selection_sort.cpp

Added
- Bubble sort
- Selection sort
- Insertion sort

adding sort algo in cpp

---

JAVA Code/PatternTriangle.java

Code for creating a triangle outline using * in java, for beginners starting off in this language.

To add a new file to the java folder named PatternTriangle.java

---

Sorting/Merging_sort.cpp

PR-Hacktoberfest2022
Hello ,
I have added Merging sort in sorting algorithms
I am looking for merging it , Kindly look into it :smile:

Added merging sort.cpp

---

Hello World Programs/HelloWorld.js
Hello World Programs/HelloWorld.ts

Added Hello World programs in JavaScript & TypeScript to the `Hello World Programs` directory of the repository

Added Hello World in JS and TS

---

selection-insertion.c

The following does a comparison between Selection and Insertion sort in terms of time complexity. It generates 5 files with 100,000 random numbers in them and then sorts these number according to the sorting algorithm used.

Adding selection-insertion.c

---

Hello World Programs/HelloWorldProgram.java

Added Hello World Program Using Java

Program to print the Hello, World

---

Sorting Algorithms/cyclicSort.cpp

Adding code to Cyclic Sort Algorithm. 
Cyclic Sort works when the array elements are in range like from [1 to n].
Time Complexity:- O(n) [worst case]
Space Complexity:- O(1)

Cyclic Sort Algorithm

---

Sorting/.cph/.radix_sort.cpp_c547f87d9848b8c440830abec42c5d45.prob
Sorting/radix_sort.cpp

Added radix sorting techniques that sorts elements of an array by comparing place value digits

Added radix sort sorting technique

---

Radix Sort.c

Radix Sort.c

---

Hello World Programs/HelloWorld.scala
Hello World Programs/HelloWorld.sh
Hello World Programs/hello_world.ex
Hello World Programs/hello_world.pl
Hello World Programs/hello_world.rb

This pull request is to add Hello World programs in:
- Bash
- Scala
- Elixir
- Perl
- Ruby

Added Hello World in Bash, Scala, Elixir, Perl & Ruby

---

Frontend Projects/Creating a form

This form is created using HTML and CSS. Any beginner looking for a form template can refer to it.

Form Creation

---

Sorting Algorithms/shell_sort.cpp

Added shell sort sorting algorithm in C++ for sorting arrays

Added shell sort sorting algorithm in C++

---

Java Programs/SubSeq.java

Print the subsequence of string problem

Added a subsequence problem in java

---

C++ Programs/missingNumber.cpp

Adding a Solution to the missing number problem with description in C++.  
Algorithm used: Cyclic Sort
Time Complexity :- O(n)
Space Complexity :- O(1)

Missing Number in Array

---

C++ Programs/search_in_rotated_sorted_array.cpp

Adding a C++ program for searching a number in a rotated sorted array.
Algorithm Used: Binary Search
Time complexity: O(log n)

Program for searching in a rotated sorted array.

---

C++ Programs/n-queen.cpp

Added the famous N queen problem and solved it using recursion + backtracking

Added N queen problem

---

Java Programs/Createfile.java

File handling in java- Creating file

Creating file programmatically in java

---

Hello World Programs/helloWorld.dart
Hello World Programs/hello_world.go
Hello World Programs/hello_world.kt
Hello World Programs/hello_world.py
Hello World Programs/hello_world.rs
Radix Sort.c

Added hello world programs in golang, kotlin, python, rust and dart.

Added hello world programs for python, go, rust, dart and kotlin

---

C++ Programs/Find_minimum_in_rotated_sorted_array.cpp

Adding a C++ program for finding minimum number in a rotated sorted array.
Algorithm Used: Binary Search
Time complexity: O(log n)

Created Find_minimum_in_rotated_sorted_array.cpp

---

Java Programs/Armstrong.java

A java program to check whether a given 3-digit number is Armstrong or not.

Armstrong Numbers

---

JAVA Code/Reverse the string Wordwise

I want to add this to the java program folder
Kindly please accept.
Thanking you

Reverse the String Wordwise

---

Array Operations/Merging to Array in sorted order.

Here i have solved the question
in optimized and easy way.
Kindly please merge this

 Merging to Array in sorted order.

---

Java Programs/Armstrong number

I want to add this in java program folder.
It basic program as well as interesting.
Please merge it
Thanking you!!

Armstrong Number

---

Java Programs/Palindrome.java

I would like to add this program to the Java Programs. This one checks whether a string is a palindrome or not. It is quite interesting, please check it out!

Palindrome Strings

---

C++ Programs/Detect cycle in an undirected graph.cpp

This is  a beginner-friendly code to detect a cycled in an undirected graph. Graph is most important topic for DSA and concept you will learn from this code will help you implement similar program.

Create Detect cycle in an undirected graph.cpp

---

PriorityQueue Implementation

Insert
Delete
getMin()
All are implemented for minimum priority Queue

Priority Queue implementation

---

Hello World Programs/hello_world.clj
Hello World Programs/hello_world.hs
Hello World Programs/hello_world.ml
Hello World Programs/hello_world.nim
Hello World Programs/hello_world.rkt

Added "Hello World" programs in these languages:

Add "Hello World" in Haskell, Clojure, OCaml, Nim and Racket

---

C++ Programs/AggressiveCows.cpp

I had uploaded code for Aggressive Cows Problem in C++

AggressiveCows.cpp

---

C++ Programs/heap sort implementation

Create heap sort implementation

---

Running Median

PriorityQueue application question

Running Median

---

C++ Programs/dp-starter.cpp

I have added a template for the Dynamic Programming questions through recursion in C++

Added DP Starter Template

---

Java Programs/Second_largest_array.java

I would like to add this to the java programs. It returns the second largest element from the given array of integers without sorting them so that the numbers may remain in their respective positions.
This one's quite simple but quirky without the usual sorting procedure.
Hope you find it interesting. Thank You!

To find the second largest element in an array

---

C Programs/dp-starter.c
C++ Programs/evaluatePostfix.cpp
C++ Programs/infToPost.cpp

I added dp starter in c, infix to postfix and evaluate postfix programs in cpp

Added c and cpp programs

---

C Programs/CountVowConsDigSpac.c

This is a program for users to count the total number of vowels, consonants, digits and spaces in a sentence that is provided by the user.

To add CountVowConsDigSpac.c to the C programs folder

---

Frontend Projects/Lorem_Ipsum Generator/index.css
Frontend Projects/Lorem_Ipsum Generator/index.html
Frontend Projects/Lorem_Ipsum Generator/index.js

In this project, you can generate random paragraphs by typing how many words you want.

Lorem Ipsum Generator

---

Ascii Value

heyyy I have added a program which is made in c language which can be used for find ascii value of variable

Added C Program

---

C Programs/multiplication_matrices.c

This C Program can be used to multiply two given matrices and returns the resultant matrix. I would like to add this one to the C Programs folder. Kindly check this out. Thank You!

Program to multiply two matrices.

---

Python Programs/bubble sort .py

Added program to do bubble sort

Python Bubble Sort

---

Python Programs/Multithreading.py

Added a small program showing multithreading operations in python

Threading in python

---

Netflix Clone/package-lock.json
Netflix Clone/package.json

A Netflix Clone that I have worked on.

Netflix Clone
